# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pickhost-cli}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ole Riesenberg"]
  s.date = %q{2009-10-04}
  s.default_executable = %q{pickhost}
  s.email = %q{or@oleriesenberg.com}
  s.executables = ["pickhost"]
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "History.txt",
     "LICENCE",
     "VERSION",
     "bin/pickhost",
     "lib/pickhost_cli.rb"
  ]
  s.homepage = %q{http://pickhost.eu}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Command line uploader for pickhost.eu}
  s.test_files = [
    "test/test_pickhost_cli.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httpclient>, [">= 2.1.5.2"])
    else
      s.add_dependency(%q<httpclient>, [">= 2.1.5.2"])
    end
  else
    s.add_dependency(%q<httpclient>, [">= 2.1.5.2"])
  end
end
